services:
  web:
    image: gptreader:lastest
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SLACK_TOKEN: ${SLACK_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
    ports:
      - ${PORT}:8080